// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASKdaXWJjcL3qlU580RJQ6P7DNYf_INZ0',
    appId: '1:919439323305:web:eee398d3a08cc7902e39b8',
    messagingSenderId: '919439323305',
    projectId: 'crumb-62c84',
    authDomain: 'crumb-62c84.firebaseapp.com',
    storageBucket: 'crumb-62c84.appspot.com',
    measurementId: 'G-WS6XFVTJF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPWSwEQZHdMOKH0YYvK-HzghGmo_rJNKo',
    appId: '1:919439323305:android:76ad1ded665a6be82e39b8',
    messagingSenderId: '919439323305',
    projectId: 'crumb-62c84',
    storageBucket: 'crumb-62c84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX64iQd9m-o3TPs9i0zDN8clmCvvxVhfs',
    appId: '1:919439323305:ios:6313a5b34619edf32e39b8',
    messagingSenderId: '919439323305',
    projectId: 'crumb-62c84',
    storageBucket: 'crumb-62c84.appspot.com',
    iosBundleId: 'com.example.crumbApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX64iQd9m-o3TPs9i0zDN8clmCvvxVhfs',
    appId: '1:919439323305:ios:6313a5b34619edf32e39b8',
    messagingSenderId: '919439323305',
    projectId: 'crumb-62c84',
    storageBucket: 'crumb-62c84.appspot.com',
    iosBundleId: 'com.example.crumbApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASKdaXWJjcL3qlU580RJQ6P7DNYf_INZ0',
    appId: '1:919439323305:web:37385d66da5d218d2e39b8',
    messagingSenderId: '919439323305',
    projectId: 'crumb-62c84',
    authDomain: 'crumb-62c84.firebaseapp.com',
    storageBucket: 'crumb-62c84.appspot.com',
    measurementId: 'G-4Y19DJEPJN',
  );

}